# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 717ff37f267bd7189f7e213b4e60b56b2322af554eb46aa304932f4c7cd575b424cd6323d92c6eae54b9e81863c9e080d47c9579d24bb3304da3df18df23abf9

test:
  secret_key_base: d00fca74b35c057c76af1e507f58e88f26d1494ad43414a885878e53a2d5fa22cc68ec3381e7f6532247c99ca6528281c578bda25f9e13468f2db926a4a9dd2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
